### ISSUE TITLE
ClassCast exception when setting fullscreen mode

### ISSUE THREAD

**Issue by vineetparikh** [fangzhonglyu/SoundLib#1]
Not sure if this is a bug or if my setup is dumb (and not sure of what information is necessary to better debug this, so will put in what info I know of so far and can check other things as necessary).

Lwjgl3WindowConfig in our setup has a function for setting fullscreen mode [here](https://github.com/fangzhonglyu/SoundLib/blob/5d823d0918c42d89549b8c0fda2b7580de810d34/desktop/src/lwjgl3/Lwjgl3WindowConfiguration.java#L150), but this requires casting our display mode to the LibGDX official display mode specified [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Graphics.java#L545).

For some reason, this is not working at least on my machine. All dependencies are correctly set up, so there are no build issues: this happens at runtime. The full error text is  
```
Exception in thread "main" java.lang.ClassCastException: class lwjgl3.Lwjgl3Graphics$Lwjgl3DisplayMode cannot be cast to class com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics$Lwjgl3DisplayMode (lwjgl3.Lwjgl3Graphics$Lwjgl3DisplayMode and com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics$Lwjgl3DisplayMode are in unnamed module of loader 'app')
	at lwjgl3.Lwjgl3WindowConfiguration.setFullscreenMode(Lwjgl3WindowConfiguration.java:150)
	at edu.cornell.gdiac.audio.desktop.backend.GDXAppSettings.getLwjgl3Configuration(GDXAppSettings.java:100)
	at edu.cornell.gdiac.audio.desktop.backend.GDXApp.<init>(GDXApp.java:39)
	at edu.cornell.gdiac.json.desktop.DesktopLauncher.main(DesktopLauncher.java:40)
```
I'm not entirely sure what's going on here, so I'll be diving in further to try and see what the main issues are when casting between the two classes. From skimming this I think maybe one way to go is to make a new object instead of casting the current one, but I don't know if there's a better way that was already found/if it's possible to cast without running into this exception.

**Comment by fangzhonglyu** [comment]
Here's a fix, and I'll package the jar again very soon. Over [here](https://github.com/fangzhonglyu/SoundLib/blob/5d823d0918c42d89549b8c0fda2b7580de810d34/desktop/src/lwjgl3/Lwjgl3WindowConfiguration.java#L22), instead of importing lwjgl3DisplayMode from the original lwjgl package, do this `import lwjgl3.Lwjgl3Graphics.Lwjgl3DisplayMode;` and it should be fixed.
